### ISSUE TITLE
constructor parameters for ZipkinClient?

### ISSUE THREAD

**Issue by hakanson** [mdsol/Medidata.ZipkinTracerModule#89]
From the [README.md](https://github.com/mdsol/Medidata.ZipkinTracerModule/blob/develop/README.md), it looks like just `IOwinContext`

`var client = new ZipkinClient(context);`

but `Medidata.ZipkinTracer.Core` (v3.0.0) from NuGet (as of 26 July 2016), it takes 3 required and 1 optional parameters

`public ZipkinClient(ILog logger, IZipkinConfig zipkinConfig, IOwinContext context, SpanCollector collector = null);`

and [ZipkinClient.cs](https://github.com/mdsol/Medidata.ZipkinTracerModule/blob/develop/src/Medidata.ZipkinTracer.Core/ZipkinClient.cs) takes 2 required and 1 optional parameters

`public ZipkinClient(IZipkinConfig zipkinConfig, IOwinContext context, SpanCollector collector = null)` 

Assuming the current source is correct, it looks like both the README and NuGet need to be updated.

**Comment by bvillanueva-mdsol** [comment]
Thanks @hakanson for raising these inconsistencies. I'm brewing up a PR to correct the readme and update the nuget within today. I'll update once it is done. Thanks!

**Comment by bvillanueva-mdsol** [comment]
We updated recently the readme and nuget. I hope it addressed the issue. @hakanson, can you confirm and close this issue? Thanks!
