### ISSUE TITLE
support for .net core

### ISSUE THREAD

**Issue by zhigang** [mdsol/Medidata.ZipkinTracerModule#92]
This can't support a .net core project.
How can fix it ?

**Comment by bvillanueva-mdsol** [comment]
@zhigang Sorry for this very late reply. We need to convert this solution to .net core and test if it works.  For now we don't have bandwidth to do that, but we are open for PR from contributors. In the future we will be heading that way though.

**Comment by zhigang** [comment]
@bvillanueva-mdsol Thanks for reply. Hope this comming soon.

**Comment by bvillanueva-mdsol** [comment]
Will inform you as soon as we have this update. Thanks @zhigang !
